<?php
require_once("koneksi.php");
$Dbobj = new DBConnection();
$querylatih = "SELECT * FROM data_latih ORDER BY id_latih ASC";
$queryuji = "SELECT * FROM data_uji ORDER BY id_uji ASC";
// $query_klas_latih = "SELECT * FROM klasifikasi_latih kl JOIN data_latih dl ON kl.id_latih = dl.id_latih";
$datalatih1s = "SELECT wp_prediksi FROM data_latih WHERE wp_prediksi='1S'";
$datalatih2s = "SELECT wp_prediksi FROM data_latih WHERE wp_prediksi='2S'";
$datalatih3s = "SELECT wp_prediksi FROM data_latih WHERE wp_prediksi='3S'";
$actlatih = mysqli_query($Dbobj->getdbconnect(), $querylatih);
$actuji = mysqli_query($Dbobj->getdbconnect(), $queryuji);
// $act_klas_latih = mysqli_query($Dbobj->getdbconnect(), $query_klas_latih);
$dataLatih = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $querylatih));
$dataUji = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $queryuji));
$dataLatih1s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $datalatih1s));
$dataLatih2s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $datalatih2s));
$dataLatih3s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $datalatih3s));
$probawal1 = $dataLatih1s / $dataLatih;
$probawal2 = $dataLatih2s / $dataLatih;
$probawal3 = $dataLatih3s / $dataLatih;
$probawal1s = round($probawal1,5);
$probawal2s = round($probawal2,5);
$probawal3s = round($probawal3,5);
$query_mkd_latih_sb1s = "SELECT mkd_latih FROM data_latih WHERE mkd_latih='SANGAT BAIK' AND wp_prediksi='1S'";
$query_mkd_latih_sb2s = "SELECT mkd_latih FROM data_latih WHERE mkd_latih='SANGAT BAIK' AND wp_prediksi='2S'";
$query_mkd_latih_sb3s = "SELECT mkd_latih FROM data_latih WHERE mkd_latih='SANGAT BAIK' AND wp_prediksi='3S'";
$mkd_latih_sb1s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkd_latih_sb1s));
$mkd_latih_sb2s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkd_latih_sb2s));
$mkd_latih_sb3s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkd_latih_sb3s));
$query_mkd_latih_b1s = "SELECT mkd_latih FROM data_latih WHERE mkd_latih='BAIK' AND wp_prediksi='1S'";
$query_mkd_latih_b2s = "SELECT mkd_latih FROM data_latih WHERE mkd_latih='BAIK' AND wp_prediksi='2S'";
$query_mkd_latih_b3s = "SELECT mkd_latih FROM data_latih WHERE mkd_latih='BAIK' AND wp_prediksi='3S'";
$mkd_latih_b1s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkd_latih_b1s));
$mkd_latih_b2s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkd_latih_b2s));
$mkd_latih_b3s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkd_latih_b3s));
$query_mkd_latih_c1s = "SELECT mkd_latih FROM data_latih WHERE mkd_latih='CUKUP' AND wp_prediksi='1S'";
$query_mkd_latih_c2s = "SELECT mkd_latih FROM data_latih WHERE mkd_latih='CUKUP' AND wp_prediksi='2S'";
$query_mkd_latih_c3s = "SELECT mkd_latih FROM data_latih WHERE mkd_latih='CUKUP' AND wp_prediksi='3S'";
$mkd_latih_c1s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkd_latih_c1s));
$mkd_latih_c2s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkd_latih_c2s));
$mkd_latih_c3s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkd_latih_c3s));
$query_mkd_latih_k1s = "SELECT mkd_latih FROM data_latih WHERE mkd_latih='KURANG' AND wp_prediksi='1S'";
$query_mkd_latih_k2s = "SELECT mkd_latih FROM data_latih WHERE mkd_latih='KURANG' AND wp_prediksi='2S'";
$query_mkd_latih_k3s = "SELECT mkd_latih FROM data_latih WHERE mkd_latih='KURANG' AND wp_prediksi='3S'";
$mkd_latih_k1s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkd_latih_k1s));
$mkd_latih_k2s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkd_latih_k2s));
$mkd_latih_k3s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkd_latih_k3s));
$query_mkd_latih_sk1s = "SELECT mkd_latih FROM data_latih WHERE mkd_latih='SANGAT KURANG' AND wp_prediksi='1S'";
$query_mkd_latih_sk2s = "SELECT mkd_latih FROM data_latih WHERE mkd_latih='SANGAT KURANG' AND wp_prediksi='2S'";
$query_mkd_latih_sk3s = "SELECT mkd_latih FROM data_latih WHERE mkd_latih='SANGAT KURANG' AND wp_prediksi='3S'";
$mkd_latih_sk1s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkd_latih_sk1s));
$mkd_latih_sk2s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkd_latih_sk2s));
$mkd_latih_sk3s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkd_latih_sk3s));
$query_ips_latih_sb1s = "SELECT ips_latih FROM data_latih WHERE ips_latih='SANGAT BAIK' AND wp_prediksi='1S'";
$query_ips_latih_sb2s = "SELECT ips_latih FROM data_latih WHERE ips_latih='SANGAT BAIK' AND wp_prediksi='2S'";
$query_ips_latih_sb3s = "SELECT ips_latih FROM data_latih WHERE ips_latih='SANGAT BAIK' AND wp_prediksi='3S'";
$ips_latih_sb1s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_ips_latih_sb1s));
$ips_latih_sb2s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_ips_latih_sb2s));
$ips_latih_sb3s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_ips_latih_sb3s));

$prob_mkd_latih_sb1s = $mkd_latih_sb1s/$dataLatih1s;
$prob_mkd_latih_sb2s = $mkd_latih_sb2s/$dataLatih2s;
$prob_mkd_latih_sb3s = $mkd_latih_sb3s/$dataLatih3s;
$prob_mkd_latih_b1s = $mkd_latih_b1s/$dataLatih1s;
$prob_mkd_latih_b2s = $mkd_latih_b2s/$dataLatih2s;
$prob_mkd_latih_b3s = $mkd_latih_b3s/$dataLatih3s;
$prob_mkd_latih_c1s = $mkd_latih_c1s/$dataLatih1s;
$prob_mkd_latih_c2s = $mkd_latih_c2s/$dataLatih2s;
$prob_mkd_latih_c3s = $mkd_latih_c3s/$dataLatih3s;
$prob_mkd_latih_k1s = $mkd_latih_k1s/$dataLatih1s;
$prob_mkd_latih_k2s = $mkd_latih_k2s/$dataLatih2s;
$prob_mkd_latih_k3s = $mkd_latih_k3s/$dataLatih3s;
$prob_mkd_latih_sk1s = $mkd_latih_sk1s/$dataLatih1s;
$prob_mkd_latih_sk2s = $mkd_latih_sk2s/$dataLatih2s;
$prob_mkd_latih_sk3s = $mkd_latih_sk3s/$dataLatih3s;



$query_ips_latih_b1s = "SELECT ips_latih FROM data_latih WHERE ips_latih='BAIK' AND wp_prediksi='1S'";
$query_ips_latih_b2s = "SELECT ips_latih FROM data_latih WHERE ips_latih='BAIK' AND wp_prediksi='2S'";
$query_ips_latih_b3s = "SELECT ips_latih FROM data_latih WHERE ips_latih='BAIK' AND wp_prediksi='3S'";
$ips_latih_b1s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_ips_latih_b1s));
$ips_latih_b2s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_ips_latih_b2s));
$ips_latih_b3s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_ips_latih_b3s));
$query_ips_latih_c1s = "SELECT ips_latih FROM data_latih WHERE ips_latih='CUKUP' AND wp_prediksi='1S'";
$query_ips_latih_c2s = "SELECT ips_latih FROM data_latih WHERE ips_latih='CUKUP' AND wp_prediksi='2S'";
$query_ips_latih_c3s = "SELECT ips_latih FROM data_latih WHERE ips_latih='CUKUP' AND wp_prediksi='3S'";
$ips_latih_c1s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_ips_latih_c1s));
$ips_latih_c2s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_ips_latih_c2s));
$ips_latih_c3s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_ips_latih_c3s));
$query_ips_latih_k1s = "SELECT ips_latih FROM data_latih WHERE ips_latih='KURANG' AND wp_prediksi='1S'";
$query_ips_latih_k2s = "SELECT ips_latih FROM data_latih WHERE ips_latih='KURANG' AND wp_prediksi='2S'";
$query_ips_latih_k3s = "SELECT ips_latih FROM data_latih WHERE ips_latih='KURANG' AND wp_prediksi='3S'";
$ips_latih_k1s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_ips_latih_k1s));
$ips_latih_k2s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_ips_latih_k2s));
$ips_latih_k3s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_ips_latih_k3s));
$query_ips_latih_sk1s = "SELECT ips_latih FROM data_latih WHERE ips_latih='SANGAT KURANG' AND wp_prediksi='1S'";
$query_ips_latih_sk2s = "SELECT ips_latih FROM data_latih WHERE ips_latih='SANGAT KURANG' AND wp_prediksi='2S'";
$query_ips_latih_sk3s = "SELECT ips_latih FROM data_latih WHERE ips_latih='SANGAT KURANG' AND wp_prediksi='3S'";
$ips_latih_sk1s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_ips_latih_sk1s));
$ips_latih_sk2s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_ips_latih_sk2s));
$ips_latih_sk3s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_ips_latih_sk3s));

$prob_ips_latih_sb1s = $ips_latih_sb1s/$dataLatih1s;
$prob_ips_latih_sb2s = $ips_latih_sb2s/$dataLatih2s;
$prob_ips_latih_sb3s = $ips_latih_sb3s/$dataLatih3s;
$prob_ips_latih_b1s = $ips_latih_b1s/$dataLatih1s;
$prob_ips_latih_b2s = $ips_latih_b2s/$dataLatih2s;
$prob_ips_latih_b3s = $ips_latih_b3s/$dataLatih3s;
$prob_ips_latih_c1s = $ips_latih_c1s/$dataLatih1s;
$prob_ips_latih_c2s = $ips_latih_c2s/$dataLatih2s;
$prob_ips_latih_c3s = $ips_latih_c3s/$dataLatih3s;
$prob_ips_latih_k1s = $ips_latih_k1s/$dataLatih1s;
$prob_ips_latih_k2s = $ips_latih_k2s/$dataLatih2s;
$prob_ips_latih_k3s = $ips_latih_k3s/$dataLatih3s;
$prob_ips_latih_sk1s = $ips_latih_sk1s/$dataLatih1s;
$prob_ips_latih_sk2s = $ips_latih_sk2s/$dataLatih2s;
$prob_ips_latih_sk3s = $ips_latih_sk3s/$dataLatih3s;


$query_mkp_latih_sb1s = "SELECT mkp_latih FROM data_latih WHERE mkp_latih='SANGAT BAIK' AND wp_prediksi='1S'";
$query_mkp_latih_sb2s = "SELECT mkp_latih FROM data_latih WHERE mkp_latih='SANGAT BAIK' AND wp_prediksi='2S'";
$query_mkp_latih_sb3s = "SELECT mkp_latih FROM data_latih WHERE mkp_latih='SANGAT BAIK' AND wp_prediksi='3S'";
$mkp_latih_sb1s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkp_latih_sb1s));
$mkp_latih_sb2s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkp_latih_sb2s));
$mkp_latih_sb3s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkp_latih_sb3s));

$query_mkp_latih_b1s = "SELECT mkp_latih FROM data_latih WHERE mkp_latih='BAIK' AND wp_prediksi='1S'";
$query_mkp_latih_b2s = "SELECT mkp_latih FROM data_latih WHERE mkp_latih='BAIK' AND wp_prediksi='2S'";
$query_mkp_latih_b3s = "SELECT mkp_latih FROM data_latih WHERE mkp_latih='BAIK' AND wp_prediksi='3S'";
$mkp_latih_b1s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkp_latih_b1s));
$mkp_latih_b2s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkp_latih_b2s));
$mkp_latih_b3s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkp_latih_b3s));
$query_mkp_latih_c1s = "SELECT mkp_latih FROM data_latih WHERE mkp_latih='CUKUP' AND wp_prediksi='1S'";
$query_mkp_latih_c2s = "SELECT mkp_latih FROM data_latih WHERE mkp_latih='CUKUP' AND wp_prediksi='2S'";
$query_mkp_latih_c3s = "SELECT mkp_latih FROM data_latih WHERE mkp_latih='CUKUP' AND wp_prediksi='3S'";
$mkp_latih_c1s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkp_latih_c1s));
$mkp_latih_c2s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkp_latih_c2s));
$mkp_latih_c3s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkp_latih_c3s));
$query_mkp_latih_k1s = "SELECT mkp_latih FROM data_latih WHERE mkp_latih='KURANG' AND wp_prediksi='1S'";
$query_mkp_latih_k2s = "SELECT mkp_latih FROM data_latih WHERE mkp_latih='KURANG' AND wp_prediksi='2S'";
$query_mkp_latih_k3s = "SELECT mkp_latih FROM data_latih WHERE mkp_latih='KURANG' AND wp_prediksi='3S'";
$mkp_latih_k1s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkp_latih_k1s));
$mkp_latih_k2s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkp_latih_k2s));
$mkp_latih_k3s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkp_latih_k3s));
$query_mkp_latih_sk1s = "SELECT mkp_latih FROM data_latih WHERE mkp_latih='SANGAT KURANG' AND wp_prediksi='1S'";
$query_mkp_latih_sk2s = "SELECT mkp_latih FROM data_latih WHERE mkp_latih='SANGAT KURANG' AND wp_prediksi='2S'";
$query_mkp_latih_sk3s = "SELECT mkp_latih FROM data_latih WHERE mkp_latih='SANGAT KURANG' AND wp_prediksi='3S'";
$mkp_latih_sk1s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkp_latih_sk1s));
$mkp_latih_sk2s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkp_latih_sk2s));
$mkp_latih_sk3s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_mkp_latih_sk3s));

$prob_mkp_latih_sb1s = $mkp_latih_sb1s/$dataLatih1s;
$prob_mkp_latih_sb2s = $mkp_latih_sb2s/$dataLatih2s;
$prob_mkp_latih_sb3s = $mkp_latih_sb3s/$dataLatih3s;
$prob_mkp_latih_b1s = $mkp_latih_b1s/$dataLatih1s;
$prob_mkp_latih_b2s = $mkp_latih_b2s/$dataLatih2s;
$prob_mkp_latih_b3s = $mkp_latih_b3s/$dataLatih3s;
$prob_mkp_latih_c1s = $mkp_latih_c1s/$dataLatih1s;
$prob_mkp_latih_c2s = $mkp_latih_c2s/$dataLatih2s;
$prob_mkp_latih_c3s = $mkp_latih_c3s/$dataLatih3s;
$prob_mkp_latih_k1s = $mkp_latih_k1s/$dataLatih1s;
$prob_mkp_latih_k2s = $mkp_latih_k2s/$dataLatih2s;
$prob_mkp_latih_k3s = $mkp_latih_k3s/$dataLatih3s;
$prob_mkp_latih_sk1s = $mkp_latih_sk1s/$dataLatih1s;
$prob_mkp_latih_sk2s = $mkp_latih_sk2s/$dataLatih2s;
$prob_mkp_latih_sk3s = $mkp_latih_sk3s/$dataLatih3s;

$query_sas_latih_sb1s = "SELECT sas_latih FROM data_latih WHERE sas_latih='SANGAT BAIK' AND wp_prediksi='1S'";
$query_sas_latih_sb2s = "SELECT sas_latih FROM data_latih WHERE sas_latih='SANGAT BAIK' AND wp_prediksi='2S'";
$query_sas_latih_sb3s = "SELECT sas_latih FROM data_latih WHERE sas_latih='SANGAT BAIK' AND wp_prediksi='3S'";
$sas_latih_sb1s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_sas_latih_sb1s));
$sas_latih_sb2s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_sas_latih_sb2s));
$sas_latih_sb3s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_sas_latih_sb3s));

$query_sas_latih_b1s = "SELECT sas_latih FROM data_latih WHERE sas_latih='BAIK' AND wp_prediksi='1S'";
$query_sas_latih_b2s = "SELECT sas_latih FROM data_latih WHERE sas_latih='BAIK' AND wp_prediksi='2S'";
$query_sas_latih_b3s = "SELECT sas_latih FROM data_latih WHERE sas_latih='BAIK' AND wp_prediksi='3S'";
$sas_latih_b1s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_sas_latih_b1s));
$sas_latih_b2s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_sas_latih_b2s));
$sas_latih_b3s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_sas_latih_b3s));
$query_sas_latih_k1s = "SELECT sas_latih FROM data_latih WHERE sas_latih='KURANG' AND wp_prediksi='1S'";
$query_sas_latih_k2s = "SELECT sas_latih FROM data_latih WHERE sas_latih='KURANG' AND wp_prediksi='2S'";
$query_sas_latih_k3s = "SELECT sas_latih FROM data_latih WHERE sas_latih='KURANG' AND wp_prediksi='3S'";
$sas_latih_k1s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_sas_latih_k1s));
$sas_latih_k2s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_sas_latih_k2s));
$sas_latih_k3s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_sas_latih_k3s));
$query_sas_latih_sk1s = "SELECT sas_latih FROM data_latih WHERE sas_latih='SANGAT KURANG' AND wp_prediksi='1S'";
$query_sas_latih_sk2s = "SELECT sas_latih FROM data_latih WHERE sas_latih='SANGAT KURANG' AND wp_prediksi='2S'";
$query_sas_latih_sk3s = "SELECT sas_latih FROM data_latih WHERE sas_latih='SANGAT KURANG' AND wp_prediksi='3S'";
$sas_latih_sk1s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_sas_latih_sk1s));
$sas_latih_sk2s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_sas_latih_sk2s));
$sas_latih_sk3s = mysqli_num_rows(mysqli_query($Dbobj->getdbconnect(), $query_sas_latih_sk3s));

$prob_sas_latih_sb1s = $sas_latih_sb1s/$dataLatih1s;
$prob_sas_latih_sb2s = $sas_latih_sb2s/$dataLatih2s;
$prob_sas_latih_sb3s = $sas_latih_sb3s/$dataLatih3s;
$prob_sas_latih_b1s = $sas_latih_b1s/$dataLatih1s;
$prob_sas_latih_b2s = $sas_latih_b2s/$dataLatih2s;
$prob_sas_latih_b3s = $sas_latih_b3s/$dataLatih3s;
$prob_sas_latih_k1s = $sas_latih_k1s/$dataLatih1s;
$prob_sas_latih_k2s = $sas_latih_k2s/$dataLatih2s;
$prob_sas_latih_k3s = $sas_latih_k3s/$dataLatih3s;
$prob_sas_latih_sk1s = $sas_latih_sk1s/$dataLatih1s;
$prob_sas_latih_sk2s = $sas_latih_sk2s/$dataLatih2s;
$prob_sas_latih_sk3s = $sas_latih_sk3s/$dataLatih3s;
// echo round($prob_sas_latih_sb1s,5);
// echo round($prob_sas_latih_sb2s,5);
// echo round($prob_sas_latih_sb3s,5);
?>